# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  api.product_handler:
      class: ApiBundle\Service\Request\ProductHandler

